name       : vis
version    : '0.6'
release    : 3
source     :
    - https://github.com/martanne/vis/releases/download/v0.6/vis-0.6.tar.gz : 9ab4a3f1c5953475130b3c286af272fe5cfdf7cbb7f9fbebd31e9ea4f34e487d
license    : ISC
component  : editor
summary    : vi-like editor based on Plan 9's structural regular expressions
description: |
    vi-like editor based on Plan 9's structural regular expressions
builddeps  :
    - pkgconfig(lua-5.3)
    - pkgconfig(ncursesw)
    - pkgconfig(termkey)
rundeps    :
    - lpeg
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
