name       : vis
version    : 0.4
release    : 1
source     :
    - https://github.com/martanne/vis/archive/v0.4.tar.gz : f11ba41cfb86dd39475960abfd12469de4da0ccfdb941f1d7680d89d987694c5
license    : ISC
component  : editor
summary    : vi-like editor based on Plan 9's structural regular expressions 
description: |
    vi-like editor based on Plan 9's structural regular expressions
builddeps  : 
    - pkgconfig(lua-5.3)
    - pkgconfig(ncursesw)
    - pkgconfig(termkey)
    - lpeg
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
