name       : vis
version    : '0.7'
release    : 7
source     :
    - https://github.com/martanne/vis/releases/download/v0.7/vis-0.7.tar.gz : 359ebb12a986b2f4e2a945567ad7587eb7d354301a5050ce10d51544570635eb
license    : ISC
component  : editor
summary    : vi-like editor based on Plan 9's structural regular expressions
description: |
    vi-like editor based on Plan 9's structural regular expressions
builddeps  :
    - pkgconfig(lua-5.3)
    - pkgconfig(ncursesw)
    - pkgconfig(termkey)
rundeps    :
    - lpeg
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
