name       : vis
version    : 0.5
release    : 2
source     :
    - https://github.com/martanne/vis/releases/download/v0.5/vis-v0.5.tar.gz : b6f617545e4e05e6c9a6187c9aa18ed62709b537ecb33d1941399ed9912d832b
license    : ISC
component  : editor
summary    : vi-like editor based on Plan 9's structural regular expressions
description: |
    vi-like editor based on Plan 9's structural regular expressions
builddeps  :
    - pkgconfig(lua-5.3)
    - pkgconfig(ncursesw)
    - pkgconfig(termkey)
    - lpeg
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
